name: build

on:
  push:
    branches: [ main, dev ]

jobs:
  build-tgt:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          wget https://github.com/typst/typst/releases/download/v23-03-28/typst-x86_64-unknown-linux-gnu.tar.gz
          tar -xvf typst-x86_64-unknown-linux-gnu.tar.gz
          typst-x86_64-unknown-linux-gnu/typst --font-path ./fonts resume.typ resume.pdf
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: compile and release new cv
          branch: feat-cv
          create_branch: true
          file_pattern: '*.pdf'
          push_options: '--force'

