name: build

on:
  push:
    branches: [ main, dev ]

jobs:
  build-tgt:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          ls
          wget https://github.com/typst/typst/releases/download/v23-03-28/typst-x86_64-unknown-linux-gnu.tar.gz
          ls
          tar -xvf typst-x86_64-unknown-linux-gnu.tar.gz
          ls
          typst --font-path ./fonts resume.typ resume.pdf
